### ISSUE TITLE
large message send doesn't appear to work

### ISSUE THREAD

**Issue by acgreek** [lesismal/nbio#40] opened 2021-06-29 13:44 UTC
https://github.com/lesismal/nbio/pull/39

**Comment by acgreek** [comment] 2021-06-29 13:54
I'm also noticed that MaxWriteBufferSize appears to be not working in that the connection is not closed when the limit is reached and setting other values doesn't appear to have an effect.

**Comment by lesismal** [comment] 2021-06-29 15:53
I am considering removing mempool and using the default allocator——append or bytes.Buffer.
mempool helps reduce memory usage for non-tls version, but cost more memory for tls version, because the llib/tls is based on std which does not use mempool, so it's hard to use mempool through out the data flow: poller -> tls -> http/websocket.
mempool makes it very very difficult for implementation and understanding even describing.

but mempool, it does reduce memory usage for high concurrent non-tls service.

**Comment by lesismal** [comment] 2021-06-29 15:55
I have also been considering continuing to use mempool to transform tls, but it does introduce another layer of complexity, making troubleshooting more difficult.

**Comment by lesismal** [comment] 2021-06-29 15:58
for most services with a high number of connections but low qps, the default allocator is sufficient enough, and it will make the parsing of http/websocket too much easier.

**Comment by lesismal** [comment] 2021-06-29 16:06
Different from the blocking mode of the standard library, in the blocking mode connection, data reading and parsing are in the same coroutine, and the same buffer can be reused in all protocol parsing, and there is no need to manage cross-coroutine buffers lifecycle, which cost us a lot in nbio.

**Comment by acgreek** [comment] 2021-06-29 17:07
Seeing same behavior without TLS. I updated the non-tls websocket client in the PR

**Comment by lesismal** [comment] 2021-06-29 17:17
I will make a non-mempool version first, then working on this bug.

**Comment by acgreek** [comment] 2021-06-29 20:51
I'm also seeing the issue with the non-http echo client server, just change the message size in the client for 4 meg and increase the timeout, it always timesout

**Comment by lesismal** [comment] 2021-06-30 03:59
> I'm also seeing the issue with the non-http echo client server, just change the message size in the client for 4 meg and increase the timeout, it always timesout

Is it a tls echo example?
I tried the tcp echo example, and it seems working fine after running it several times.
The example of tls-websocket reports "bad record MAC" error, it seems to be a problem with llib/tls, I will continue to debug it.

**Comment by acgreek** [comment] 2021-06-30 13:53
it was a problem with kqueue. see PR

**Comment by acgreek** [comment] 2021-06-30 13:54
are you able to run the autobahn sweat on linux?

**Comment by lesismal** [comment] 2021-06-30 14:17
> are you able to run the autobahn sweat on linux?

merged.

I see this memory use, it may make buffer cached by nbio.Conn dirty
https://github.com/lesismal/llib/blob/master/std/crypto/tls/conn.go#L990
but seems not fix all the problem, I'll continue to check other code.

**Comment by lesismal** [comment] 2021-06-30 14:18
> are you able to run the autobahn sweat on linux?

I did not run autobahn, but write other examples and reproduce the problem.

**Comment by acgreek** [comment] 2021-06-30 14:31
I think the remaining issues are performance related. We have some expensive copies done when the write buffer is large

specifically in conn_unix.go 
```
			c.leftSize += left
			leftData := b
			if n > 0 {
				leftData = mempool.Malloc(left)
				copy(leftData, b[n:])
				c.g.onWriteBufferFree(c, b)
			}
			c.writeBuffers = append(c.writeBuffers, leftData)
			c.modWrite()		
```

Either we get rid of the mempool or we rework them so whole code base works off something more flexible. Thinking 
```
Malloc(size ) *Buffer
Resize(buff * Buffer, size)
Free(*Buffer)

func BufferWrap(buf []byte) *Buffer {
     return  &Buffer{
          data: buf,
          fromPool:true,
     } 
}

type Buffer struct{
    data []byte
    offset int
    fromPool bool
}
func(b * Buffer) Remaining() []byte {
   b.data[b.offset]
}
func (b* Buffer) Consume(size int) {
   b.offset += size
}
```

**Comment by lesismal** [comment] 2021-06-30 14:43
> I think the remaining issues are performance related. We have some expensive copies done when the write buffer is large
> 
> specifically in conn_unix.go
> 
> ```
> 			c.leftSize += left
> 			leftData := b
> 			if n > 0 {
> 				leftData = mempool.Malloc(left)
> 				copy(leftData, b[n:])
> 				c.g.onWriteBufferFree(c, b)
> 			}
> 			c.writeBuffers = append(c.writeBuffers, leftData)
> 			c.modWrite()		
> ```
> 
> Either we get rid of the mempool or we rework them so whole code base works off something more flexible. Thinking
> 
> ```
> Malloc(size ) *Buffer
> Resize(buff * Buffer, size)
> Free(*Buffer)
> 
> func BufferWrap(buf []byte) *Buffer {
>      return  &Buffer{
>           data: buf,
>           fromPool:true,
>      } 
> }
> 
> type Buffer struct{
>     data []byte
>     offset int
>     fromPool bool
> }
> func(b * Buffer) Remaining() []byte {
>    b.data[b.offset]
> }
> func (b* Buffer) Consume(size int) {
>    b.offset += size
> }
> ```

ye it is, especially for tls. I've make a non-mempool branch, it obviously promote response time of tls service:
https://github.com/lesismal/nbio/tree/http_no_mempool
I need to confirm more details of this branch, then will merge this.

**Comment by acgreek** [comment] 2021-06-30 14:50
I'm going to try to implement my example code above

**Comment by lesismal** [comment] 2021-06-30 14:57
> I'm going to try to implement my example code above

ok.

ok.
note that there are too many difficulties in reading and writing, upstream and downstream, memory transfer between different goroutines. such as reading, tls read/write, http parsing/encoding, websocket parsing/encoding, nbio.Conn.Write

**Comment by lesismal** [comment] 2021-06-30 16:32
> > are you able to run the autobahn sweat on linux?
> 
> merged.
> 
> I see this memory use, it may make buffer cached by nbio.Conn dirty
> https://github.com/lesismal/llib/blob/master/std/crypto/tls/conn.go#L990
> but seems not fix all the problem, I'll continue to check other code.

I run autobahn with the latest version and get failures of large payload. 
https://github.com/lesismal/nbio/pull/41 has not solved the problem.

**Comment by lesismal** [comment] 2021-06-30 16:48
> I'm going to try to implement my example code above

I'm thinking about another way to use memory buffers:
1. wherever need to allocate a memory buffer, get it from the pool
2. wherever use over a memory buffer, put it into the pool
3. just use append() when the buffer proceeds between different layers

**Comment by lesismal** [comment] 2021-07-01 18:40
[4m-profile.zip](https://github.com/lesismal/nbio/files/6750103/4m-profile.zip)

check this profile, it's not nbio.Conn.Write cost most of the memory usage, but the http/websocket parser does.
```golang
go tool  pprof -http=":6060" .\profile
```

![image](https://user-images.githubusercontent.com/40462947/124173317-74f87680-dadd-11eb-80bd-fcfee4dd53a2.png)

![image](https://user-images.githubusercontent.com/40462947/124173349-82156580-dadd-11eb-8a88-4bd5aff9e389.png)

I am going to rewrite the code of parser memory buffer usage, which may conflict with your optimization about nbio.Conn's write buffer.

**Comment by lesismal** [comment] 2021-07-02 13:26
done with the new memory buffer usage, please try the latest. not use OnWriteBufferRelease and seems good now.
there seems to be some bug with nbio.Conn's write cache, I'm going on to review the code related with nbio.Conn's write cache.

**Comment by lesismal** [comment] 2021-07-03 04:33
found the tls pool bug and fixed:
https://github.com/lesismal/llib/commit/8e8f7da2f61c19a529ed19a1d939281ea7029109#r52993273

for the next: https://github.com/lesismal/nbio/pull/43

**Closed** 2021-07-03 14:07 UTC
